config/routes.rb
Rails.application.routes.draw do

  resources :busforms do
      resources :stops do
      end
    end  


      root "busforms#index"

  get 'new/signup'=> 'new#signup'
  get 'new/bustickets'=> 'new#bustickets'
  get 'new/cabs'=> 'new#cabs'
  get 'new/citybus'=> 'new#citybus'
  get 'new/flights'=> 'new#flights'
  get 'new/home'=> 'new#home'
  get 'new/metro'=> 'new#metro'
  get 'new/train'=> 'new#train'

end





 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/busform.rb
class Busform < ApplicationRecord
	has_many:stops, dependent: :nullify
end

app/models/stop.rb
class Stop < ApplicationRecord
  belongs_to :busform

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/busforms_controller.rb
    class BusformsController < ApplicationController
  before_action :set_busform, only: [:show, :edit, :update, :destroy]

  # GET /busforms
  # GET /busforms.json
  def index
    @search = Busform.search(params[:q])
    @busforms = @search.result
  #store all the clients that match the name searched    
  end
  

  # GET /busforms/1
  # GET /busforms/1.json
  def show
  end

  # GET /busforms/new
  def new
    @busform = Busform.new
  end

  # GET /busforms/1/edit
  def edit
  end

  # POST /busforms
  # POST /busforms.json
  def create
    @busform = Busform.new(busform_params)

    respond_to do |format|
      if @busform.save
        format.html { redirect_to @busform, notice: 'Busform was successfully created.' }
        format.json { render :show, status: :created, location: @busform }
      else
        format.html { render :new }
        format.json { render json: @busform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /busforms/1
  # PATCH/PUT /busforms/1.json
  def update
    respond_to do |format|
      if @busform.update(busform_params)
        format.html { redirect_to @busform, notice: 'Busform was successfully updated.' }
        format.json { render :show, status: :ok, location: @busform }
      else
        format.html { render :edit }
        format.json { render json: @busform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /busforms/1
  # DELETE /busforms/1.json
  def destroy
    @busform.destroy
    respond_to do |format|
      format.html { redirect_to busforms_url, notice: 'Busform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_busform
      @busform = Busform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def busform_params
      params.require(:busform).permit(:title, :description)
    end
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def home
  end

  def cabs
  end

  def citybus
  end

  def metro
  end

  def bustickets
  end

  def train
  end

  def flights
  end

end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
	before_action :set_busform
	before_action :set_stop, except: [:create]

	def create
		@stop = @busform.stops.create(stop_params)
		redirect_to @busform
	end
	

	def destroy
		@stop = @busform.stops.find(params[:id])
		if @stop.destroy
			flash[:success] = "Stop was deleted."
		else
		    flash[:error] = "Unable to delete stop."
		end
		redirect_to @busform
	end

	private

	def set_busform
		@busform = Busform.find(params[:busform_id])

	end

	def set_stop
		@stop = @busform.stops.find(params[:id])
		@search = @busform.stops.search(params[:q])
		@stop = @search.result

	end

	

	def stop_params
		params[:stop].permit(:content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/busforms_helper.rb
module BusformsHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/busforms/_form.html.erb
<%= simple_form_for(@busform) do |f| %>
  <%= f.error_notification %>
    <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>

<% end %>

app/views/busforms/edit.html.erb
   <h1>Editing Busform</h1>
<div class = "sforms">
	<%= render 'form', busform: @busform %>
</div>


<div class="links">
	<%= link_to 'Show', @busform %> |
	<%= link_to 'Back', busforms_path %>
	<%= link_to 'Cancel', busforms_path %>
</div>

app/views/busforms/index.html.erb
<br>
<br>



  <div class="banner bus-banner">
    <!-- container -->
    <div class="container">
      <div class="col-md-8 banner-right">
                        <div id ="map">
                        </div>
                        
        <!---metromain--->
      </div>
      <div class="col-md-4 banner-left">
        <div class="sap_tabs">  
          <div class="booking-info about-booking-info">
            <h2>Catch A Bus</h2>
          </div>
          <div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">  
              <!---->        
                  <div class="facts about-facts">
                    <div class="booking-form">
                                <div class=""book_date"">

      <input id="txtSource" class="maploc" type="text"placeholder="Enter an origin location"> 

      <br>
      <br>

      <input id="txtDestination" class="maploc" type="text"placeholder="Enter a destination location">                      
                                            
                                        
                                        </div>
                                     
                                     <div class="clearfix"></div>
                                </div>
                                <br>
                                <div class=""reservation"">
                                            
                                            <input type="button" value="Search Buses" onclick="GetRoute()" />
                                          
                                        </div>

                                        <div id="dvDistance"></div>
                             
                                     <div class="clearfix"></div>
  

  </div>
  </div>
  </div>
  </div>
  </div>
  </div>

  <br>
  <br>
  <br>
<<<<<<< HEAD
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"></script>
<script type="text/javascript">

var directionsDisplay = new google.maps.DirectionsRenderer();
var directionsService = new google.maps.DirectionsService();
var map = new google.maps.Map(document.getElementById('map'), map);
directionsDisplay.setMap(map);
    new google.maps.places.SearchBox(document.getElementById('txtSource'));
    new google.maps.places.SearchBox(document.getElementById('txtDestination'));

    
var request = {
      origin: txtSource,
      destination: txtdestination,
      travelMode:  google.maps.TravelMode.TRANSIT

=======

<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"></script>
<script type="text/javascript">

var directionsDisplay = new google.maps.DirectionsRenderer();
var directionsService = new google.maps.DirectionsService();
var map = new google.maps.Map(document.getElementById('map'), map);
directionsDisplay.setMap(map);
    new google.maps.places.SearchBox(document.getElementById('txtSource'));
    new google.maps.places.SearchBox(document.getElementById('txtDestination'));

    
var request = {
      origin: txtSource,
      destination: txtdestination,
      travelMode:  google.maps.TravelMode.TRANSIT

>>>>>>> 9bf03231e72f175931f52af0970d159f9cc5724b
  };


function GetRoute() {
    var hyderabad = new google.maps.LatLng(17.3850, 78.4867);
    var map = {
        mapTypeControl: false,
        zoom: 7,
        center: hyderabad
    };

 map = new google.maps.Map(document.getElementById('map'), map);  
    directionsDisplay.setMap(map);
    

 
 
    //*********DIRECTIONS AND ROUTE**********************//
    source = document.getElementById("txtSource").value;
    destination = document.getElementById("txtDestination").value;
 
    var request = {
        origin: source,
        destination: destination,
        travelMode: google.maps.TravelMode.TRANSIT
    };
    directionsService.route(request, function (response, status) {
        if (status == google.maps.DirectionsStatus.OK) {
            directionsDisplay.setDirections(response);
        }
    });
 
    //*********DISTANCE AND DURATION**********************//
    var service = new google.maps.DistanceMatrixService();
    service.getDistanceMatrix({
        origins: [source],
        destinations: [destination],
        travelMode: google.maps.TravelMode.TRANSIT,
        unitSystem: google.maps.UnitSystem.METRIC,
        avoidHighways: false,
        avoidTolls: false
    }, function (response, status) {
        if (status == google.maps.DistanceMatrixStatus.OK && response.rows[0].elements[0].status != "ZERO_RESULTS") {
            var distance = response.rows[0].elements[0].distance.text;
            var duration = response.rows[0].elements[0].duration.text;
            var dvDistance = document.getElementById("dvDistance");
           dvDistance.innerHTML = "";
            dvDistance.innerHTML += "Distance: " + distance + "<br />";
            dvDistance.innerHTML += "Duration:" + duration;
 
        } else {
            alert("Unable to find the distance via road.");
        }
    });
}
</script>


<<<<<<< HEAD
<%= search_form_for @search do |f| %>
=======
  <%= search_form_for @search do |f| %>
>>>>>>> 9bf03231e72f175931f52af0970d159f9cc5724b
<div class="container">  
<div class="col-md-4">
<div class="field">
  <%= f.label :title_cont, "Search By Bus Number" %>
  <%= f.text_field :title_cont %>
</div>

<div class="actions"><%= f.submit "Search" %> </div>
</div>
</div>
<% end %>


<% @busforms.each do |busform| %>


  <div class="col-md-4">
  <div class="busno_row">
    <h3 class="busform_title"><%= link_to busform.title, busform %></h3>
    <p class="busform_sub_title"><%= busform.description %></p>
  </div>
  </div> 
<% end %>


<div class="links">
  <%= link_to "New Bus Form", new_busform_path %>
  <% link_to 'Delete', busforms_path(@busform), method: :delete, data: { confirm: "Are u sure"} %>
  
  <%= link_to 'Back', busforms_path %>
</div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/busforms/new.html.erb
<h1>New Busform</h1>

<div class="sforms">
	<%= render 'form', busform: @busform %>
</div>

<div class="links">
	<%= link_to 'Back', busforms_path %>
</div>

app/views/busforms/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<h2 class="busform_title"><%= @busform.title %></h2>
<p class="busform_sub_title"><%= @busform.description %></p>

<p>
  <strong>BUS STOPS</strong>
</p>

<div class = "container">
<div class = "col-lg-4">

<div id="stops_wrapper">
 <%= render @busform.stops %>
	<div id="sform">
		<%= render "stops/form" %>
	</div>
</div>
</div>

						<div class = "col-lg-6">

												<div id ="map">
												</div>
						</div>						

</div>

<script>




function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          mapTypeControl: false,
          center: {lat: 17.3850, lng: 78.4867},

          zoom: 14  
        });

        new AutocompleteDirectionsHandler(map);
      }

function AutocompleteDirectionsHandler(map) {
        this.map = map;
        this.originPlaceId = null;
        this.destinationPlaceId = null;
        this.travelMode = 'WALKING';
        var originInput = document.getElementById('origin-input');
        var destinationInput = document.getElementById('destination-input');
        this.directionsService = new google.maps.DirectionsService;
        this.directionsDisplay = new google.maps.DirectionsRenderer;
        this.directionsDisplay.setMap(map);

        var originAutocomplete = new google.maps.places.Autocomplete(
            originInput, {placeIdOnly: true});
        var destinationAutocomplete = new google.maps.places.Autocomplete(
            destinationInput, {placeIdOnly: true});
        
		
		
        this.setupPlaceChangedListener(originAutocomplete, 'ORIG');
        this.setupPlaceChangedListener(destinationAutocomplete, 'DEST');

      }

AutocompleteDirectionsHandler.prototype.setupClickListener = function(id, mode) {
        var radioButton = document.getElementById(id);
        var me = this;
        radioButton.addEventListener('click', function() {
          me.travelMode = mode;
          me.route();
        });
      };

      AutocompleteDirectionsHandler.prototype.setupPlaceChangedListener = function(autocomplete, mode) {
        var me = this;
        autocomplete.bindTo('bounds', this.map);
        autocomplete.addListener('place_changed', function() {
          var place = autocomplete.getPlace();
          if (!place.place_id) {
            window.alert("Please select an option from the dropdown list.");
            return;
          }
          if (mode === 'ORIG') {
            me.originPlaceId = place.place_id;
          } else {
            me.destinationPlaceId = place.place_id;
          }
          me.route();
        });

      };

      AutocompleteDirectionsHandler.prototype.route = function() {
        if (!this.originPlaceId || !this.destinationPlaceId) {
          return;
        }
        var me = this;

        this.directionsService.route({
          origin: {'placeId': this.originPlaceId},
          destination: {'placeId': this.destinationPlaceId},
          travelMode: this.travelMode
        }, function(response, status) {
          if (status === 'OK') {
            me.directionsDisplay.setDirections(response);
          } else {
            window.alert('Directions request failed due to ' + status);
          }
        });
      };

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwMxo4Zne-NBl8A8h-MBYlgjxppC_5rLc&libraries=places&callback=initMap"async defer>
</script>


<%= link_to 'Edit', edit_busform_path(@busform) %> |
<%= link_to 'Delete', busform_path(@busform), method: :delete, data: { confirm: "Are you sure?" }  %> |
	
	<%= link_to 'Back', busforms_path %>

app/views/layouts/_transport_footer.erb
<!-- //footer -->
	<div class="footer-bottom-grids">
		<!-- container -->
		<div class="container">
				<div class="footer-bottom-top-grids">
					<div class="col-md-4 footer-bottom-left">
						<h4>Download our mobile Apps</h4>
						<div class="d-apps">
							<ul>
								<li><a href="#"><%= image_tag("propics/app1.png") %></a></li>
								<li><a href="#"><%= image_tag("propics/app2.png") %></a></a></li>
								<li><a href="#"><%= image_tag("propics/app3.png") %></a></a></li>
							</ul>
						</div>
					</div>
					<div class="col-md-4 footer-bottom-left">
						<h4>We Accept</h4>
						<div class="a-cards">
							<ul>
								<li><a href="#"><%= image_tag("propics/c1.png") %></a></li>
								<li><a href="#"><%= image_tag("propics/c2.png") %></a></a></li>
								<li><a href="#"><%= image_tag("propics/c3.png") %></a></a></li>
							</ul>
						</div>
					</div>
					<div class="col-md-4 footer-bottom-left">
						<h4>Follow Us</h4>
						<div class="social">
							<ul>
								<li><a href="#" class="facebook"> </a></li>
								<li><a href="#" class="facebook twitter"> </a></li>
								<li><a href="#" class="facebook chrome"> </a></li>
								<li><a href="#" class="facebook dribbble"> </a></li>
							</ul>
						</div>
					</div>
					<div class="clearfix"> </div>
					<div class="copyright">
						<p>Copyrights <a href="">Fastron</a></p>
					</div>
				</div>
		</div>
		
		
	</div>

app/views/layouts/_transport_header.erb
<nav class= "navbar navbar-default">	
 <div class="nav-icon1" id="nav-icon1">
<span></span>
  <span></span>
  <span></span>
 </div>

<div>
	<div class="homeicon"><a href="/new/home.html"><%= image_tag("propics/home_icon.png") %></a></div>
    <div class="android"><a href=""><%= image_tag("propics/android.png") %></a></div>
	<div class="apple"><a href=""><%= image_tag("propics/apple.png") %></a></div>

    

<div class="contra">

 

<a id="modal_trigger" href="#modal" class=""><%= image_tag("propics/usericon_white.png") %></a>

</div>
</div>
</nav>
		
		<div id="modal" class="popupContainer" style="display:none;">
		<div class="col-sm-12">
				<header class="popupHeader">
						<span class="header_title">Login</span>
						<span class="modal_close">x</span>
				</header>

				<section class="popupBody">
						<!-- Social Login -->
						<div class="social_login">
								<div class="">
										<a href="#" class="social_box fb">
												<span class="icon"><i class="fa fa-facebook"></i></span>
												<span class="icon_title">Connect with Facebook</span>

										</a>

										<a href="#" class="social_box google">
												<span class="icon"><i class="fa fa-google-plus"></i></span>
												<span class="icon_title">Connect with Google</span>
										</a>
								</div>

								<div class="centeredText">
										<span>Or use your Email address</span>
								</div>

								<div class="action_btns">
										<div class="one_half"><a href="#" id="login_form" class="btn">Login</a></div>
										<div class="one_half last"><a href="#" id="register_form" class="btn">Sign up</a></div>
								</div>
						</div>

						<!-- Username & Password Login form -->
						<div class="user_login">
								<form>
										<label>Email / Username</label>
										<input type="text" />
										<br />

										<label>Password</label>
										<input type="password" />
										<br />

										<div class="checkbox">
												<input id="remember" type="checkbox" />
												<label for="remember">Remember me on this computer</label>
										</div>

										<div class="action_btns">
												<div class="one_half"><a href="#" class="btn back_btn"><i class="fa fa-angle-double-left"></i> Back</a></div>
												<div class="one_half last"><a href="#" class="btn btn_red">Login</a></div>
										</div>
								</form>

								<a href="#" class="forgot_password">Forgot password?</a>
						</div>

						<!-- Register Form -->
						<div class="user_register">
								<form>
										<label>Full Name</label>
										<input type="text" />
										<br />

										<label>Email Address</label>
										<input type="email" />
										<br />

										<label>Password</label>
										<input type="password" />
										<br />

										<div class="checkbox">
												<input id="send_updates" type="checkbox" />
												<label for="send_updates">Send me occasional email updates</label>
										</div>

										<div class="action_btns">
												<div class="one_half"><a href="#" class="btn back_btn"><i class="fa fa-angle-double-left"></i> Back</a></div>
												<div class="one_half last"><a href="#" class="btn btn_red">Register</a></div>
										</div>
								</form>
						</div>
				</section>
		</div>
		</div>

		



  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='https://andwecode.com/wp-content/uploads/2015/10/jquery.leanModal.min_.js'></script>

    <%= javascript_include_tag 'index' %>



    

</div>

	

<div class="responsive-menu">
<ul>
    <li><a href="/new/home.html">Home</a></li><br>
    <li><a href="#about">About</a></li><br>
    <li><a href="#contact">Contact</a></li><br>
    <li><a href=""><%= image_tag("propics/android.png") %>Android</a></li><br>
	<li><a href=""><%= image_tag("propics/apple.png") %>Ios</a></li><br>
	<li><a href=""><%= image_tag("propics/usericon_white.png") %>Login</a></li><br>
	

  </ul>
</div>





 
<script>
        $(document).ready(function(){
	$('#nav-icon1').click(function(){
          $('.responsive-menu').toggleClass('expand')
            $(this).toggleClass('open');
		
	});
});
	



</script>


<link rel='stylesheet prefetch' href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,700italic,400italic'>
<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css'>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>


<!-- END HEADER -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Faston</title>

      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <%= yield :meta %>
      <meta name="robots" content="index,follow">
    <link rel="icon" type="image/png" href="/assets/images/propics/world.png">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel='stylesheet prefetch' href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,700italic,400italic'>
<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css'>


    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'stylesheet' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  


  
</head>



<body>



<%= render :partial => 'layouts/transport_header' %>
    	<%= yield %>
<%= render :partial => 'layouts/transport_footer' %>

   
	

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

app/views/new/citybus.html.erb
<div class="banner bus-banner">
    <!-- container -->
    <div class="container">
      <div class="col-md-8 banner-right">
                        <div id ="map">
                        </div>
                        
        <!---metromain--->
      </div>
      <div class="col-md-4 banner-left">
        <div class="sap_tabs">  
          <div class="booking-info about-booking-info">
            <h2>Travel By A City Bus</h2>
          </div>
          <div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">  
              <!---->        
                  <div class="facts about-facts">
                    <div class="booking-form">
                                <div class=""book_date"">

      <input id="origin-input" class="maploc" type="text"placeholder="Enter an origin location">

      <br>
      <br>

          <input id="destination-input" class="maploc" type="text"placeholder="Enter a destination location">                         
                                            
                                        
                                        </div>
                                     
                                     <div class="clearfix"></div>
                                </div>
                                <br>
                                <div class=""reservation"">
                                            
                                            <input type="text" name="distance" id="distance" placeholder="Total Kms" readonly="true" />
                                          
                                        </div>
                                     
                                     <div class="clearfix"></div>
  

  </div>
  </div>
  </div>
  </div>
  </div>
  </div>
	





<br>
<br>


<script>




function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          mapTypeControl: false,
          center: {lat: 17.3850, lng: 78.4867},

          zoom: 13
        });

        new AutocompleteDirectionsHandler(map);
      }

function AutocompleteDirectionsHandler(map) {
        this.map = map;
        this.originPlaceId = null;
        this.destinationPlaceId = null;
        this.travelMode = 'TRANSIT';
        var originInput = document.getElementById('origin-input');
        var destinationInput = document.getElementById('destination-input');
        this.directionsService = new google.maps.DirectionsService;
        this.directionsDisplay = new google.maps.DirectionsRenderer;
        this.directionsDisplay.setMap(map);

        var originAutocomplete = new google.maps.places.Autocomplete(
            originInput, {placeIdOnly: true});
        var destinationAutocomplete = new google.maps.places.Autocomplete(
            destinationInput, {placeIdOnly: true});
        
		
		
        this.setupPlaceChangedListener(originAutocomplete, 'ORIG');
        this.setupPlaceChangedListener(destinationAutocomplete, 'DEST');

      }

AutocompleteDirectionsHandler.prototype.setupClickListener = function(id, mode) {
        var radioButton = document.getElementById(id);
        var me = this;
        radioButton.addEventListener('click', function() {
          me.travelMode = mode;
          me.route();
        });
      };

      AutocompleteDirectionsHandler.prototype.setupPlaceChangedListener = function(autocomplete, mode) {
        var me = this;
        autocomplete.bindTo('bounds', this.map);
        autocomplete.addListener('place_changed', function() {
          var place = autocomplete.getPlace();
          if (!place.place_id) {
            window.alert("Please select an option from the dropdown list.");
            return;
          }
          if (mode === 'ORIG') {
            me.originPlaceId = place.place_id;
          } else {
            me.destinationPlaceId = place.place_id;
          }
          me.route();
        });

      };

      AutocompleteDirectionsHandler.prototype.route = function() {
        if (!this.originPlaceId || !this.destinationPlaceId) {
          return;
        }
        var me = this;

        this.directionsService.route({
          origin: {'placeId': this.originPlaceId},
          destination: {'placeId': this.destinationPlaceId},
          travelMode: this.travelMode
        }, function(response, status) {
          if (status === 'OK') {
            me.directionsDisplay.setDirections(response);
          } else {
            window.alert('Directions request failed due to ' + status);
          }
        });
      };

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwMxo4Zne-NBl8A8h-MBYlgjxppC_5rLc&libraries=places&callback=initMap"async defer>
</script>

<br>
<br>
<br>
<br>
<br>

app/views/stops/_form.html.erb
<%= form_for([@busform, @busform.stops.build]) do |f| %>
	<%= f.text_field :content, placeholder: " New Stop" %>
	<%= f.submit %>
<% end %>

app/views/stops/_stop.html.erb
<div class="container">
  <div class=""col-md-8">
	 <div class="stop">
	 <p><%= stop.content %></p>
	 <p>
	 <%= link_to "Delete", busform_stop_path(@busform, stop.id), method: :delete, data: { confirm: "Are you sure?" } %>

	 </p>
	     </div>


	
	</div>
 </div>